---
title: "#MakeoverMonday"
author: "Jake"
date: "June 26, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r workspace}
library(tidyverse)
library(googlesheets)
library(forcats)
library(extrafont)
library(gridExtra)
library(xkcd)
#time series
library(TTR)
library(lubridate)
options(scipen = 999)

challenge_week <- 26
```

```{r scrape table}
#google sheet to read in
  google_key <- 
    gs_key("1XpDdIfrHLaL5Iiu7x8eVAIlDuq83zwUNqJSUsYSAh18")

#get names of worksheets
  gs_ws_ls(google_key)

#get twitter links to scrape
  data_raw <- 
    gs_read(google_key, 
            ws = as.character(challenge_week), 
            lookup = T) %>% 
    data.frame()
  
  data_clean <-
    data_raw  %>% 
    mutate(Metric = paste(trade_type, vehicle_type, sep = " - "),
           date = mdy(date)) %>% 
    select(3:5)
  
  
  ggplot(data_clean) +
    facet_grid(. ~ Metric, scales = "free_y") +
    geom_col(aes(x = date, y = N))
    
```

#time series
```{r}
ts_transform <-
  function(x){
    #x = "Gold Price"
    
    ts_data <-
      data_clean %>% 
      filter(Metric == x)
    
    ts_values <-
      ts_data %>% 
      .$N %>% log(.) %>% 
      ts(frequency = 12, c(2008, 1)) %>% 
      stl(s.window = 'periodic')

    cbind(ts_data, as.data.frame(ts_values$time.series))
}

measures <- unique(data_clean$Metric)

data_final <-
  rbind(ts_transform(measures[1]),
        ts_transform(measures[2]),
        ts_transform(measures[3]),
        ts_transform(measures[4])) %>%
  gather(key = Measure, value = Value, -c(date,Metric)) %>%
  mutate(Measure = factor(Measure, 
                levels = c("N", "trend", "seasonal", "remainder")))
```

```{r}
ggplot(data_final) +
  facet_wrap(~Measure, scales = "free") +
  geom_line(aes(x = date, y = Value, color = Metric))

ggplot(data_final) +
  facet_wrap(Metric ~ Measure, scales = "free", ncol = 4) +
  geom_line(aes(x = date, y = Value))

data_raw %>%
  filter(complete.cases(.)) %>% 
  mutate(Ord = row_number()) %>% 
  ggplot(aes(x = `Gold Price`, y = `Oil Price`,
             color = Year)) + 
  geom_smooth(alpha = .1) +
  geom_point(size = 1, alpha = .5) +
  geom_path()
```

```{r}
#https://learnr.wordpress.com/2010/05/10/ggplot2-waterfall-charts/

whatHappened <- 
  superstore %>% 
  select(Order, Order.ID, Cost, ListPrice, Discount) %>%
  mutate(Cost = -Cost) %>% 
  gather(key = Event, value = Value, Cost:Discount) %>% 
  mutate(Event = factor(Event, levels = c("Cost", "ListPrice", "Discount"))) %>% 
  arrange(Order) %>% 
  mutate(Order2 = row_number(),
         End = cumsum(Value), 
         Start = lag(End, default = 0)) %>% 
  group_by(Order) %>% 
  mutate(Cost2 = ifelse(Event == "Cost", Start, 
                        ifelse(Event == "ListPrice", lag(Start),
                               ifelse(Event == "Discount", lag(Start, 2), NA)))) %>% 
  ungroup()
```

```{r}

colors <- c("#aba5a5", "#85c5a2", "#ea7e26")

ggplot(whatHappened[1:(3*8),], aes(Order)) + 
  geom_hline(yintercept = 0) +
  geom_rect(aes(x = Order2, fill = Event,
                xmin = Order2 - 0.45, 
                xmax = Order2 + 0.45, 
                ymin = End, 
                ymax = Start)) +
  scale_fill_manual(values = colors) +
  geom_rect(aes(x = Order2,
                xmin = Order2 - 0.47, 
                xmax = Order2 + 0.47, 
                ymin = Cost2,
                ymax = Cost2+1), 
            color = "NA", fill = "black") + 
  ylab("$ of Event") +
  ylim(-210,200) +
  theme_minimal()  +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title = element_blank(),
        axis.ticks.x = element_blank()#
        ,legend.position = "none"
  )

ggsave(file="ggWaterfall.png", width=4.5, height=3)
```


```{r}
#https://learnr.wordpress.com/2010/05/10/ggplot2-waterfall-charts/

whatHappened2 <- 
  superstore %>% 
  select(Order, Order.ID, Cost, ListPrice) %>%
  mutate(Cost = -Cost) %>% 
  gather(key = Event, value = Value, Cost:ListPrice) %>% 
  mutate(Event = factor(Event, levels = c("Cost", "ListPrice"))) %>% 
  arrange(Order) %>% 
  mutate(Order2 = row_number(),
         End = cumsum(Value), 
         Start = lag(End, default = 0)) %>% 
  group_by(Order) %>% 
  mutate(Cost2 = ifelse(Event == "Cost", Start, 
                        ifelse(Event == "ListPrice", lag(Start), NA))) %>% 
  ungroup()
```

```{r}

ggplot(whatHappened2[1:(2*8),], aes(Order)) + 
  geom_rect(aes(x = Order2, fill = Event,
                xmin = Order2 - 0.45, 
                xmax = Order2 + 0.45, 
                ymin = End, 
                ymax = Start)) +
  scale_fill_manual(values = colors) +
  geom_rect(aes(x = Order2,
                xmin = Order2 - 0.47, 
                xmax = Order2 + 0.47, 
                ymin = Cost2,
                ymax = Cost2+1), 
            color = "NA", fill = "black") + 
  geom_hline(yintercept = 0) +
  ylab("$ of Event") +
  ylim(-210,200) +
  theme_minimal()+
  theme(panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title = element_blank(),
        axis.ticks.x = element_blank()#
        ,legend.position = "none"
  )

ggsave(file="ggWaterfall2.png", width=4.5, height=3)
```
