---
title: "#MakeoverMonday"
author: "Jake"
date: "May 1, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r workspace}
library(tidyverse)
library(googlesheets)
library(forcats)
library(extrafont)
library(gridExtra)  #combines ggplot charts
#library(extrafontdb)
#library(Rttf2pt1)
library(xkcd)
#time series
library(TTR)
library(lubridate)
library(plotly)
options(scipen = 999)

challenge_week <- 2
```

```{r scrape table}
#google sheet to read in
  google_key <- 
    gs_key("1XpDdIfrHLaL5Iiu7x8eVAIlDuq83zwUNqJSUsYSAh18")

#get names of worksheets
  gs_ws_ls(google_key)

#get twitter links to scrape
  data_raw <- 
    gs_read(google_key, 
            ws = as.character(challenge_week), 
            lookup = T) %>% 
    filter(year >= 2008) %>% 
    rename(Value = units_sold_millions) %>% 
    mutate(quarter = substr(quarter, 2,3),
           reporting_date = paste0(substr(year, 3,4), "-", quarter),
           running_total = cumsum(Value),
           time = year >= 2012)

```

Challenge: iPhone Sales over time, units sold in millions
```{r}
cut_by <- 4 #length(data_raw)
```

###Time series decomposition
```{r}
#bring in fonts
  font_import(pattern="xkcd", prompt = F)
  fonttable()

```


```{r}
######
  pre2012 <-
    filter(data_raw, time == F) %>% 
    .$Value %>%
    ts(frequency = cut_by)
  
  pre2012_table <-
    as.data.frame(stl(pre2012, s.window = 'periodic')$time.series) %>% 
    mutate(time = "2008 - 2011")

######
  post2012 <-
    filter(data_raw, time == T) %>% 
    .$Value %>%
    ts(frequency = cut_by)
  
  post2012_table <-
    as.data.frame(stl(post2012, s.window = 'periodic')$time.series) %>% 
    mutate(time = "2012-2016")

#####
data_ts_decomp <-
    pre2012_table %>% 
  rbind(post2012_table) %>% 
  cbind(select(data_raw, running_total, quarter, reporting_date)) %>%
#  mutate_each(funs(as.integer), trend:remainder) %>%
  mutate(original = as.numeric(trend + seasonal + remainder)) %>%
  gather(key = Measure, value = Value, -c(time, quarter:reporting_date)) %>%
  mutate(Measure = factor(Measure, 
                levels = c("original", "trend", "seasonal", "remainder", "running_total")))

outliers <- 
  data_ts_decomp %>%
  filter(Measure == "remainder") %>%
  group_by(time) %>% 
  mutate(SD = sd(Value),
         Outlier = abs(Value) > SD) 

#write.csv(ts3, "Sales.csv", row.names = F)
```

#xkcd + dataman
```{r}
datascaled <- data.frame(x=c(0,20),y=c(0,1000))
p <- ggplot(data=datascaled, aes(x=x,y=y)) + geom_point()


mapping <- aes(measure = Measure,
               time = time,
               x = x,
               y = y,
               scale = scale,
               ratioxy = ratioxy,
               angleofspine = angleofspine,
               anglerighthumerus = anglerighthumerus,
               anglelefthumerus = anglelefthumerus,
               anglerightradius = anglerightradius,
               angleleftradius = angleleftradius,
               anglerightleg = anglerightleg,
               angleleftleg = angleleftleg,
               angleofneck = angleofneck,
               color = color )

dataman <- data.frame( x= "08-Q2", y= 600,
                       Measure = "running_total",
                       time = "2008 - 2011",
                       scale = 200,
                       ratioxy = 0.008,
                       angleofspine = -1.7 ,
                       anglerighthumerus = -0.52,
                       anglelefthumerus = 3.66,
                       anglerightradius = 0,
                       angleleftradius = -0.78,
                       angleleftleg = 4.97 ,
                       anglerightleg = 4.45,
                       angleofneck = 4.39,
                       color=c("A"))
p + xkcdman(mapping, dataman)

xkcd_quote <-
  data.frame(reporting_date = "08-Q1",
             Value = 750,
             Measure = "running_total",
             time = "2008 - 2011")
```
##titles
```{r}
#function for wrapping text
  wrapper <- 
    function(x, ...) {
      paste(strwrap(x, ...), collapse = "\n")
    }

plot_title <-
  "With over 1 BILLION iPhones sold between 2008-2016, how much more can the iPhone sell?" %>% 
  wrapper(., width = 60)

plot_subtitle <- 
  "\nFrom Statista. All Y-axis values are in the millions. The release of the 4S in Q4 2011, marked a shift in the volume of sales the iPhone has each quarter. After two very high Q1 sales periods in 2016 and total units in the billions, it looks like it might be hard for Apple to keep up the pace. Author: Jake Riley\n" %>% 
  wrapper(., width = 85)

plot_caption <-
"The observations in the remainder section with orange circles behind the dots indicate outliers beyond 1 standard deviation"%>% 
  wrapper(., width = 85)

```

###Create plot
```{r}  
  ggplot() +
      facet_grid(Measure ~ time, scales = "free") +
    #identify outlier range
      geom_line(data = outliers, aes(x = reporting_date, y = SD), group = 1) +
      geom_line(data = outliers, aes(x = reporting_date, y = -SD), group = 1) +
      geom_point(data = filter(outliers, Outlier == T), 
                 aes(x = reporting_date, y = Value), 
                 shape = "o", size = 8, color = "orange") +
    #plot time series lines
      geom_line(data = data_ts_decomp,
                aes(x = reporting_date, y = Value, group = 1)) + #, fill = quarter)) + 
      geom_point(data = data_ts_decomp, 
               aes(x = reporting_date, y = Value, color = quarter), size = 3) +
      scale_color_manual(values = c("navyblue", "grey50", "grey65", "grey70", "black")) +
    #dataman
      xkcdman(mapping, dataman) +
      geom_text(data = xkcd_quote, aes(x = reporting_date, y = Value),
                family = "xkcd", hjust = .2, size = 5,
                label = "If we market these in utero, how \ncan we keep the 'i' prefix?") +
    #plot aesthetics
      geom_hline(yintercept = 0) +
      labs(title = plot_title, subtitle = plot_subtitle, caption = plot_caption) +
      theme(text = element_text(family="xkcd", size = 14),
            strip.text.y = element_text(size = 14),
            strip.background = element_rect(color = "grey40"),
            plot.title = element_text(hjust = 1,size = 18, color = "grey30", face = "bold"),
            plot.subtitle = element_text(hjust = 1, size = 14, color = "grey50"),
            plot.caption = element_text(hjust = 1, size = 14, color = "grey50"),
            axis.ticks = element_blank(),
            axis.title = element_blank(),
            axis.text.x = element_blank(), #text(angle = 90, size = 12),
            panel.background = element_rect(fill = "white",color = "grey50"))

#ggplotly(p)
```
