---
title: "#MakeoverMonday"
author: "Jake"
date: "May 1, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r workspace}
setwd("C:/Users/foxtr/Desktop/makeoverMonday/weekly scripts")
library(tidyverse)
library(httr)
library(googlesheets)
library(forcats)
library(extrafont)
library(xkcd)
options(scipen = 999)
#library(lubridate)
#library(stringr)

challenge_week <- 17
```

```{r scrape table}
#google sheet to read in
  google_key <- 
    gs_key("1XpDdIfrHLaL5Iiu7x8eVAIlDuq83zwUNqJSUsYSAh18")

#get names of worksheets
  gs_ws_ls(google_key)

#get twitter links to scrape
  data_raw <- 
    gs_read(google_key, 
            ws = as.character(challenge_week), 
            lookup = T) %>% 
    mutate(Skill = gsub(" and ", " and\n", Skill))
```

Challenge: 70 skills, 15 countries. Not all skills rated for each country. Top 25 for 2014 & 2015, Top 10 for 2016
```{r}
data_raw %>% 
  group_by(Country, Year) %>% 
  summarise(nSkills = n_distinct(Skill)) %>% 
  spread(key = Year, value = nSkills)

table(data_raw$Country)

cutoff <- 5

data_plot_all <-
  data_raw %>% 
  group_by(Skill, Year) %>% 
  filter(n_distinct(Country) >= cutoff) %>%
  group_by(Skill) %>% 
  filter(n_distinct(Year) == 3) %>% 
  ungroup() %>% 
  mutate(Skill = factor(Skill))

data_plot_single <-
  data_plot_all %>% 
  group_by(Skill, Year) %>% 
  summarise(year_median = median(Rank) %>% round(., 2),
            n_countries = n_distinct(Country)) %>% 
  group_by(Skill) %>% 
  arrange(Year) %>% 
  mutate(growth = first(year_median) - last(year_median),
         growth = ifelse(Year !=2016, NA,
                         paste0("Growth: ", 
                         ifelse(growth > 0, "+", ""), growth))) %>% 
  ungroup()

#  do(mutate(., year_median = median(Rank))) %>% 

factor_skill <-
  data_plot_single %>% 
  select(Skill:year_median) %>% 
  filter(Year == 2016) %>% 
  arrange(year_median, Skill)

factor_levels <- fct_inorder(factor_skill$Skill)

data_plot_all$Skill <-
  factor(data_plot_all$Skill, levels = factor_levels, ordered = T)

data_plot_single$Skill <-
  factor(data_plot_single$Skill, levels = factor_levels, ordered = T)


levels(data_plot_single$Skill) %>% head()
```

##Plots
```{r}
#bring in fonts
  font_import(pattern="xkcd", prompt = F)

#function for wrapping text
  wrapper <- 
    function(x, ...) {
      paste(strwrap(x, ...), collapse = "\n")
    }

plot_title <- "Statistical Analysis and Data Mining was ranked highest on average in 2016 while User Interface Design has seen the most growth 2014 - 2016"  %>% wrapper(., width = 70)

  
plot_subtitle <- "\nFrom LinkedIn's annual Top Skills Reports - 2014, 2015, and 2016. Skills are ranked by average ranking in 2016. Only skills that were ranked each year by 5 or more countries are included.\nMarker indicates median values.\n\nAuthor: Jake Riley\n" %>% wrapper(., width = 90)
  
  
ggplot(data_plot_all) +
  facet_grid(Skill~., switch = 'y') +
  geom_count(aes(x = Rank, y = factor(Year), color = factor(Year)),
             alpha = .5) +
  scale_color_manual(values = c("grey65", "grey45", "darkblue"),
                     name = "Year") +
  scale_size_continuous(range = c(2, 4), breaks= c(1,5,10), name="Countries") +
  geom_point(data = data_plot_single,
             aes(x = year_median, y = factor(Year), color = factor(Year)),
             shape = "I", size = 6) +
  geom_text(data = data_plot_single,
            aes(x = -2, y = factor(Year), label = n_countries),
             size = 4, family="xkcd") +  
  geom_text(data = data_plot_single,
            aes(x = 25, y = factor(Year), 
                label = growth),
             size = 4, color = "grey50", hjust = 1) +  
  theme(text = element_text(family="xkcd", size = 14),
        strip.text.y = element_text(angle = 180, size = 14),
        strip.background = element_rect(color = "grey40"),
        plot.title = element_text(hjust = 1,size = 16, color = "grey30", face = "bold"),
        plot.subtitle = element_text(hjust = 1, size = 14, color = "grey50"),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        panel.background = element_rect(fill = "white",color = "grey50"))+
  ggtitle(label = plot_title, subtitle = plot_subtitle)

```
