---
title: "Killed by a Bear"
subtitle: "2019 week 21"
author: "jake riley"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Source: [data.world](https://data.world/makeovermonday/2019w21)

```{r}
library(data.world)
library(tidyverse)
library(simplecolors)

raw_data <-
  data.world::query(
    qry_sql("SELECT * FROM north_america_bear_killings"),
    "makeovermonday/2019w21"
  ) %>% 
  data.frame() %>% 
  mutate(
    n = 1,
    decade = round(year, -1),
    gender = str_extract(gender, "\\w+"),
    gender = fct_infreq(gender),
    season_int = month %/% 3,
    season = 
      case_when(
        season_int %in% c(0, 4) ~ "winter",
        season_int == 1 ~ "spring", 
        season_int == 2 ~ "summer",
        season_int == 3 ~ "fall",
        TRUE ~ NA_character_
      ),
    month_fct = factor((month)),
    month_abb = month(month, label = TRUE),
    month_fct = fct_relevel(month_abb, "Jan", "Feb", after = Inf),
    season_fct = fct_reorder(season, as.integer(month_fct), max)
  )

levels(raw_data$season_fct)
```

```{r}
theme_all <-
  theme(
    panel.background = element_rect(fill = "white"),
    panel.border = element_rect(color = "grey90"),
    panel.grid = element_blank()
  )

main <- {
  ggplot(raw_data, aes(decade, fct_rev(month_fct), color = season_fct)) +
  geom_count() +
  scale_color_manual(values = sc_across("TORB")) +
  scale_x_continuous(breaks = seq(1900, 2020, by = 20)) +
  theme_all +
  guides(color = FALSE) +
  labs(color = "", y = "") +
  theme(
    plot.margin = unit(c(0,0,0,0), "cm"),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    legend.justification = c(0, 1), 
    legend.position = c(0.02, 0.15),
    legend.direction = "horizontal",
    legend.background = element_rect(color = "grey90")
  )
}

p2 <- 
  ggplot(raw_data, aes(decade)) +
  geom_bar(aes(fill = decade %in% c(1980, 2000, 2010))) +
  theme_all +
  scale_fill_manual(values = sc("grey2", "mutedred3")) +
  scale_x_continuous(
    breaks = seq(1900, 2020, by = 20),
    expand = expand_scale(0.01)
  ) +
  labs(y = "") +
  theme(
    legend.position = "none",
    plot.margin = unit(c(0,0,0,0), "cm"),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.title.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.x = element_blank()
  )

p3 <- {
  ggplot(raw_data, aes(fct_rev(month_fct), fill = season_fct)) +
  geom_bar() +
  coord_flip() +
  scale_fill_manual(values = sc_across("TORB")) +
  theme_all +
  theme(
    plot.margin = unit(c(0,0,0,0), "cm"),
    legend.position = "none",
    axis.title.y = element_blank(),
    axis.ticks.y = element_blank()
  )
}

blank <- ggplot() + geom_blank() + theme_void()

plot_title <-
  grid::textGrob(
    "Although bear attacks are rare, the 80s & early 00s had the\nhighest number of deaths\n  ",
    gp = grid::gpar(fontface = "bold", fontsize = 14), 
    hjust = 0, x = 0.05
  )


plot_caption <-
  grid::textGrob(
    "\nSource: Vox, via Wikipedia",
    gp = grid::gpar(col = "grey50"), 
    hjust = -0.7
  )

gridExtra::grid.arrange(
  p2, blank, main, p3,
  ncol = 2, nrow = 2,
  widths = c(3, 1), 
  heights = c(1, 3),
  top = plot_title,
  bottom = plot_caption
)
```
