---
title: "replicating packed bubble charts in Tableau"
author: "jake riley,  @yake_84"
date: "July 29, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r workspace}
library(tidyverse)
options(scipen = 999)

points_start <-
  #create a base table
    tibble(circumf = seq(0, 2*pi, length.out = 7),
           x1 = sin(circumf)*100,
           y1 = cos(circumf)*100, 0) %>% 
  #find next point for each vertex   
    mutate(x2 = lead(x1, default = 0),
           y2 = lead(y1, default = 1),
           vertex = row_number()) %>%
  #round evrything  
    mutate_all(.funs = funs(round(., 0))) %>% 
    select(vertex, x1, y1, x2, y2) 
```

```{r test_plot}
ggplot(points_start, aes(x1, y1, label = vertex)) +
  geom_polygon(alpha = .2) +
  geom_point(size = 10, color = "white", stroke = 1) +
  geom_text() +
  coord_fixed()
```


```{r for_loop}
#base table for the for loop
  points_all <-
    tibble(layer = 0, 
           layer_hex_ord = 1, 
           vertex = 1, 
           mids = 0,
           x = 0, 
           y = 0)

#for loop to generate expanded grid of points
  for(i in 1:6){
    points_loop <-
        #create table for each vertex and midpoints in-between
          expand.grid(vertex = 1:6,
                      mids = 0:(i-1),
                      KEEP.OUT.ATTRS = F) %>% 
          arrange(vertex) %>%
        #join in the coordinates
          left_join(points_start) %>%
        #add layer level, order per layer and final coordinates
          mutate(layer = i,
                 layer_hex_ord = row_number(),
                 x = (x1 + mids/i * (x2 - x1))*i,
                 y = (y1 + mids/i * (y2 - y1)) * i) %>% 
          select(one_of(colnames(points_all)))
      
    #create master table
      points_all <-
        rbind(points_all, points_loop)
  }
```

```{r for_loop2}
points_spiral_table <-
  points_all[1,] %>% 
  mutate(ord_offset = 0,
         hex_ord_offset = 0)

#generate spiral/star arangement
 for(i in 1:6){
    #i = 3
    points_base <-
      points_all %>% 
      filter(layer == i)
    
    points_base1 <-
      filter(points_base, layer_hex_ord >= 2) %>% 
      rbind(filter(points_base, layer_hex_ord < 2)) %>% 
      mutate(ord_offset = row_number(),
             hex_ord_offset = ord_offset %% (i), 
             hex_ord_offset = ifelse(hex_ord_offset == 0, i,
                                     hex_ord_offset)) 
     
    #ggplot(points_base1) +geom_text(aes(x = x, y = y, label = hex_ord_offset))
    
    points_spiral_table <-
      rbind(points_spiral_table, points_base1)
 }

```

```{r}
#final dataset
points_final <-
  points_spiral_table %>%
  arrange(layer, layer_hex_ord) %>% 
  mutate(by_layer = row_number()) %>% 
  arrange(layer, hex_ord_offset, ord_offset) %>% 
  mutate(by_star = row_number()) %>% 
  select(-hex_ord_offset, -ord_offset) %>% 
  arrange(x+1000, y) %>% 
  mutate(by_x = row_number()) %>% 
  arrange(y+1000, x) %>% 
  mutate(by_y = row_number()) %>% 
  arrange(vertex, layer, layer_hex_ord) %>% 
  mutate(by_vertex = row_number()) %>% 
  select(by_star, x, y, contains("by_"), everything()) %>% 
  arrange(by_star)
```

```{r charts}
plot_points <-
  function(var_color, var_label){
    #var_color = "layer"; var_label = "by_layer"
    points_final %>% 
    mutate_(col_color = var_color,
            col_label = var_label) %>% 
    arrange(col_color, col_label) %>% 
    ggplot(aes(x, y, label = round(col_label, 0))) +
      geom_path(aes(group = 1),#col_color, color = factor(col_color)), 
                size = 2, alpha = .2) +
      geom_point(aes(0,0), size = 14) +
      geom_point(aes(fill = factor(col_color)), size = 10, 
                 alpha = .4, pch = 21) +
      geom_text(size = 3) +
      guides(color = F, fill = F) +
      coord_fixed() +
      theme_void()
}

plot_points("layer", "by_layer")
plot_points("mids", "mids")
plot_points("vertex", "by_vertex")
plot_points("layer", "by_star")
plot_points("x", "by_x")
plot_points("y", "by_y")

#colnames
  # "by_star"  "x"     "y"
  # "by_layer" "by_x"  "by_y"  "by_vertex"     
  # "layer"    "layer_hex_ord" "vertex"  "mids"

write_csv(points_final, "packed_bubbles.csv")
```
